// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cling/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorBody 是主站稳定错误响应的公共载体。
// 业务错误码由主站定义，不能依赖底层框架或中台的错误文本。
type ErrorBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorBody) Reset() {
	*x = ErrorBody{}
	mi := &file_cling_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorBody) ProtoMessage() {}

func (x *ErrorBody) ProtoReflect() protoreflect.Message {
	mi := &file_cling_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorBody.ProtoReflect.Descriptor instead.
func (*ErrorBody) Descriptor() ([]byte, []int) {
	return file_cling_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorBody) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorBody) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_cling_v1_common_proto protoreflect.FileDescriptor

const file_cling_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15cling/v1/common.proto\x12\rcling.main.v1\"X\n" +
	"\tErrorBody\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestIdB%Z#ai-business-service/api/cling/v1;v1b\x06proto3"

var (
	file_cling_v1_common_proto_rawDescOnce sync.Once
	file_cling_v1_common_proto_rawDescData []byte
)

func file_cling_v1_common_proto_rawDescGZIP() []byte {
	file_cling_v1_common_proto_rawDescOnce.Do(func() {
		file_cling_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cling_v1_common_proto_rawDesc), len(file_cling_v1_common_proto_rawDesc)))
	})
	return file_cling_v1_common_proto_rawDescData
}

var file_cling_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cling_v1_common_proto_goTypes = []any{
	(*ErrorBody)(nil), // 0: cling.main.v1.ErrorBody
}
var file_cling_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cling_v1_common_proto_init() }
func file_cling_v1_common_proto_init() {
	if File_cling_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cling_v1_common_proto_rawDesc), len(file_cling_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cling_v1_common_proto_goTypes,
		DependencyIndexes: file_cling_v1_common_proto_depIdxs,
		MessageInfos:      file_cling_v1_common_proto_msgTypes,
	}.Build()
	File_cling_v1_common_proto = out.File
	file_cling_v1_common_proto_goTypes = nil
	file_cling_v1_common_proto_depIdxs = nil
}
