// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cling/v1/errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerationErrorCode 固定三种不可合并的生成门禁结果。
// 它们虽然部分共享 HTTP 状态，但客户端需要据此展示不同的引导动作。
type GenerationErrorCode int32

const (
	GenerationErrorCode_GENERATION_ERROR_CODE_UNSPECIFIED GenerationErrorCode = 0
	GenerationErrorCode_ACCOUNT_BINDING_REQUIRED          GenerationErrorCode = 1
	GenerationErrorCode_VIP_REQUIRED                      GenerationErrorCode = 2
	GenerationErrorCode_INSUFFICIENT_FUNDS                GenerationErrorCode = 3
)

// Enum value maps for GenerationErrorCode.
var (
	GenerationErrorCode_name = map[int32]string{
		0: "GENERATION_ERROR_CODE_UNSPECIFIED",
		1: "ACCOUNT_BINDING_REQUIRED",
		2: "VIP_REQUIRED",
		3: "INSUFFICIENT_FUNDS",
	}
	GenerationErrorCode_value = map[string]int32{
		"GENERATION_ERROR_CODE_UNSPECIFIED": 0,
		"ACCOUNT_BINDING_REQUIRED":          1,
		"VIP_REQUIRED":                      2,
		"INSUFFICIENT_FUNDS":                3,
	}
)

func (x GenerationErrorCode) Enum() *GenerationErrorCode {
	p := new(GenerationErrorCode)
	*p = x
	return p
}

func (x GenerationErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerationErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cling_v1_errors_proto_enumTypes[0].Descriptor()
}

func (GenerationErrorCode) Type() protoreflect.EnumType {
	return &file_cling_v1_errors_proto_enumTypes[0]
}

func (x GenerationErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerationErrorCode.Descriptor instead.
func (GenerationErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_cling_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_cling_v1_errors_proto protoreflect.FileDescriptor

const file_cling_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x15cling/v1/errors.proto\x12\rcling.main.v1*\x84\x01\n" +
	"\x13GenerationErrorCode\x12%\n" +
	"!GENERATION_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ACCOUNT_BINDING_REQUIRED\x10\x01\x12\x10\n" +
	"\fVIP_REQUIRED\x10\x02\x12\x16\n" +
	"\x12INSUFFICIENT_FUNDS\x10\x03B%Z#ai-business-service/api/cling/v1;v1b\x06proto3"

var (
	file_cling_v1_errors_proto_rawDescOnce sync.Once
	file_cling_v1_errors_proto_rawDescData []byte
)

func file_cling_v1_errors_proto_rawDescGZIP() []byte {
	file_cling_v1_errors_proto_rawDescOnce.Do(func() {
		file_cling_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cling_v1_errors_proto_rawDesc), len(file_cling_v1_errors_proto_rawDesc)))
	})
	return file_cling_v1_errors_proto_rawDescData
}

var file_cling_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cling_v1_errors_proto_goTypes = []any{
	(GenerationErrorCode)(0), // 0: cling.main.v1.GenerationErrorCode
}
var file_cling_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cling_v1_errors_proto_init() }
func file_cling_v1_errors_proto_init() {
	if File_cling_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cling_v1_errors_proto_rawDesc), len(file_cling_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cling_v1_errors_proto_goTypes,
		DependencyIndexes: file_cling_v1_errors_proto_depIdxs,
		EnumInfos:         file_cling_v1_errors_proto_enumTypes,
	}.Build()
	File_cling_v1_errors_proto = out.File
	file_cling_v1_errors_proto_goTypes = nil
	file_cling_v1_errors_proto_depIdxs = nil
}
