// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ai-business-service/internal/biz"
	"ai-business-service/internal/biz/creations"
	"ai-business-service/internal/biz/entitlement"
	"ai-business-service/internal/biz/ledger"
	"ai-business-service/internal/biz/outbox"
	"ai-business-service/internal/conf"
	"ai-business-service/internal/data"
	"ai-business-service/internal/integrations/contentreview"
	"ai-business-service/internal/integrations/generation"
	"ai-business-service/internal/server"
	"ai-business-service/internal/worker"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, security *conf.Security, integrations *conf.Integrations, logger *slog.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer)
	httpServer := server.NewHTTPServer(confServer)
	moduleRegistry := biz.NewModuleRegistry()
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	txRunner := data.NewTxRunner(dataData)
	localSchemaInitializer := data.NewLocalSchemaInitializer(dataData)
	userRepository := data.NewUserRepository(dataData)
	userReaderAdapter := creations.NewUserReaderAdapter(userRepository)
	subscriptionReader := data.NewSubscriptionRepository(dataData)
	usecase := entitlement.NewUsecase()
	entitlementEvaluatorAdapter := creations.NewEntitlementEvaluatorAdapter(usecase)
	repository := data.NewCreationRepository(dataData)
	ledgerRepository := data.NewLedgerRepository(dataData)
	ledgerUsecase := ledger.NewUsecase(ledgerRepository, txRunner)
	reservationUsecaseAdapter := creations.NewReservationUsecaseAdapter(ledgerUsecase)
	outboxRepository := data.NewOutboxRepository(dataData)
	writer := outbox.NewWriter(outboxRepository)
	creationsUsecase := creations.NewUsecase(userReaderAdapter, subscriptionReader, entitlementEvaluatorAdapter, repository, reservationUsecaseAdapter, writer, txRunner)
	submissionStore := data.NewGenerationSubmissionRepository(dataData)
	client, err := generation.NewConfiguredClient(security, integrations)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	reviewer := contentreview.NewConfiguredReviewer(integrations)
	generationSubmissionWorker := worker.NewDefaultGenerationSubmissionWorker(outboxRepository, submissionStore, ledgerUsecase, txRunner, client, reviewer)
	app, err := newApp(logger, grpcServer, httpServer, moduleRegistry, txRunner, localSchemaInitializer, creationsUsecase, generationSubmissionWorker)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
