// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Server       *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data         *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Security     *Security              `protobuf:"bytes,3,opt,name=security,proto3" json:"security,omitempty"`
	Integrations *Integrations          `protobuf:"bytes,4,opt,name=integrations,proto3" json:"integrations,omitempty"`
	Worker       *Worker                `protobuf:"bytes,5,opt,name=worker,proto3" json:"worker,omitempty"`
	// 空值兼容既有本地配置；显式值仅允许 local / production。
	Environment   string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Bootstrap) GetIntegrations() *Integrations {
	if x != nil {
		return x.Integrations
	}
	return nil
}

func (x *Bootstrap) GetWorker() *Worker {
	if x != nil {
		return x.Worker
	}
	return nil
}

func (x *Bootstrap) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mongo         *Data_Mongo            `protobuf:"bytes,1,opt,name=mongo,proto3" json:"mongo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetMongo() *Data_Mongo {
	if x != nil {
		return x.Mongo
	}
	return nil
}

type Security struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话签名密钥；配置文件只能保存本地占位值，生产密钥只通过受控环境注入。
	SessionSigningKey string `protobuf:"bytes,1,opt,name=session_signing_key,json=sessionSigningKey,proto3" json:"session_signing_key,omitempty"`
	// 主站请求生成中台时使用的 HMAC 密钥。
	GenerationRequestHmacKey string `protobuf:"bytes,2,opt,name=generation_request_hmac_key,json=generationRequestHmacKey,proto3" json:"generation_request_hmac_key,omitempty"`
	// 生成中台回调主站时使用的 HMAC 密钥。
	GenerationCallbackHmacKey string `protobuf:"bytes,3,opt,name=generation_callback_hmac_key,json=generationCallbackHmacKey,proto3" json:"generation_callback_hmac_key,omitempty"`
	// PayCores 回调主站时使用的独立 HMAC 密钥，禁止复用生成回调密钥。
	PaycoresCallbackHmacKey string `protobuf:"bytes,9,opt,name=paycores_callback_hmac_key,json=paycoresCallbackHmacKey,proto3" json:"paycores_callback_hmac_key,omitempty"`
	// 主站请求 PayCores 创建订单时使用的独立 HMAC 密钥，禁止复用回调密钥。
	PaycoresRequestHmacKey string `protobuf:"bytes,10,opt,name=paycores_request_hmac_key,json=paycoresRequestHmacKey,proto3" json:"paycores_request_hmac_key,omitempty"`
	// Argon2id 内存成本，单位 KiB；低于安全下限时服务拒绝启动。
	PasswordMemoryKib uint32 `protobuf:"varint,4,opt,name=password_memory_kib,json=passwordMemoryKib,proto3" json:"password_memory_kib,omitempty"`
	// Argon2id 时间成本；低于安全下限时服务拒绝启动。
	PasswordTimeCost uint32 `protobuf:"varint,5,opt,name=password_time_cost,json=passwordTimeCost,proto3" json:"password_time_cost,omitempty"`
	// Argon2id 并行度；运行时转换前会验证可安全表示为 uint8。
	PasswordParallelism uint32 `protobuf:"varint,6,opt,name=password_parallelism,json=passwordParallelism,proto3" json:"password_parallelism,omitempty"`
	// 每条密码凭据随机盐的字节数。
	PasswordSaltBytes uint32 `protobuf:"varint,7,opt,name=password_salt_bytes,json=passwordSaltBytes,proto3" json:"password_salt_bytes,omitempty"`
	// Argon2id 派生密钥的字节数。
	PasswordKeyBytes uint32 `protobuf:"varint,8,opt,name=password_key_bytes,json=passwordKeyBytes,proto3" json:"password_key_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Security) GetSessionSigningKey() string {
	if x != nil {
		return x.SessionSigningKey
	}
	return ""
}

func (x *Security) GetGenerationRequestHmacKey() string {
	if x != nil {
		return x.GenerationRequestHmacKey
	}
	return ""
}

func (x *Security) GetGenerationCallbackHmacKey() string {
	if x != nil {
		return x.GenerationCallbackHmacKey
	}
	return ""
}

func (x *Security) GetPaycoresCallbackHmacKey() string {
	if x != nil {
		return x.PaycoresCallbackHmacKey
	}
	return ""
}

func (x *Security) GetPaycoresRequestHmacKey() string {
	if x != nil {
		return x.PaycoresRequestHmacKey
	}
	return ""
}

func (x *Security) GetPasswordMemoryKib() uint32 {
	if x != nil {
		return x.PasswordMemoryKib
	}
	return 0
}

func (x *Security) GetPasswordTimeCost() uint32 {
	if x != nil {
		return x.PasswordTimeCost
	}
	return 0
}

func (x *Security) GetPasswordParallelism() uint32 {
	if x != nil {
		return x.PasswordParallelism
	}
	return 0
}

func (x *Security) GetPasswordSaltBytes() uint32 {
	if x != nil {
		return x.PasswordSaltBytes
	}
	return 0
}

func (x *Security) GetPasswordKeyBytes() uint32 {
	if x != nil {
		return x.PasswordKeyBytes
	}
	return 0
}

type Integrations struct {
	state      protoimpl.MessageState   `protogen:"open.v1"`
	Generation *Integrations_Generation `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Paycores   *Integrations_Paycores   `protobuf:"bytes,2,opt,name=paycores,proto3" json:"paycores,omitempty"`
	AppStore   *Integrations_AppStore   `protobuf:"bytes,3,opt,name=app_store,json=appStore,proto3" json:"app_store,omitempty"`
	// 配置缺失时允许普通用户服务启动；受限用户提交将在审核阶段安全失败并冲正。
	ContentReview *Integrations_ContentReview `protobuf:"bytes,4,opt,name=content_review,json=contentReview,proto3" json:"content_review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integrations) Reset() {
	*x = Integrations{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integrations) ProtoMessage() {}

func (x *Integrations) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integrations.ProtoReflect.Descriptor instead.
func (*Integrations) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Integrations) GetGeneration() *Integrations_Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *Integrations) GetPaycores() *Integrations_Paycores {
	if x != nil {
		return x.Paycores
	}
	return nil
}

func (x *Integrations) GetAppStore() *Integrations_AppStore {
	if x != nil {
		return x.AppStore
	}
	return nil
}

func (x *Integrations) GetContentReview() *Integrations_ContentReview {
	if x != nil {
		return x.ContentReview
	}
	return nil
}

type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollInterval  *durationpb.Duration   `protobuf:"bytes,1,opt,name=poll_interval,json=pollInterval,proto3" json:"poll_interval,omitempty"`
	BatchSize     int32                  `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Worker) GetPollInterval() *durationpb.Duration {
	if x != nil {
		return x.PollInterval
	}
	return nil
}

func (x *Worker) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Mongo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MongoDB 连接串仅指向 Go 主站独立实例，不能复用 Node 的连接串。
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// 数据库名固定为 cling_main，以隔离 Node 的业务集合。
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// 本地事务依赖单节点副本集 rs0。
	ReplicaSet string `protobuf:"bytes,3,opt,name=replica_set,json=replicaSet,proto3" json:"replica_set,omitempty"`
	// 账本与预扣需要多文档事务，禁止关闭该开关。
	TransactionsRequired bool `protobuf:"varint,4,opt,name=transactions_required,json=transactionsRequired,proto3" json:"transactions_required,omitempty"`
	// 仅 Docker Compose 本地运行时允许使用 mongo 服务名；默认拒绝。
	DockerLocalProfile bool `protobuf:"varint,5,opt,name=docker_local_profile,json=dockerLocalProfile,proto3" json:"docker_local_profile,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Data_Mongo) Reset() {
	*x = Data_Mongo{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Mongo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Mongo) ProtoMessage() {}

func (x *Data_Mongo) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Mongo.ProtoReflect.Descriptor instead.
func (*Data_Mongo) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Mongo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Data_Mongo) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Data_Mongo) GetReplicaSet() string {
	if x != nil {
		return x.ReplicaSet
	}
	return ""
}

func (x *Data_Mongo) GetTransactionsRequired() bool {
	if x != nil {
		return x.TransactionsRequired
	}
	return false
}

func (x *Data_Mongo) GetDockerLocalProfile() bool {
	if x != nil {
		return x.DockerLocalProfile
	}
	return false
}

type Integrations_Generation struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// 主站自己的回调基地址，禁止依赖生成中台默认回调。
	CallbackBaseUrl string `protobuf:"bytes,2,opt,name=callback_base_url,json=callbackBaseUrl,proto3" json:"callback_base_url,omitempty"`
	// 中台租户准入密钥；与请求 HMAC、回调 HMAC 分离，不能写入执行载荷。
	ApiKey string `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// 新步骤准入选择；空值仅兼容 local_execution_v2，不影响历史步骤归属。
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// 独立账号与认证；可与上述 local 配置共存以排空历史步骤。
	PolarstarB2B  *Integrations_PolarStarB2B `protobuf:"bytes,5,opt,name=polarstar_b2b,json=polarstarB2b,proto3" json:"polarstar_b2b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integrations_Generation) Reset() {
	*x = Integrations_Generation{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integrations_Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integrations_Generation) ProtoMessage() {}

func (x *Integrations_Generation) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integrations_Generation.ProtoReflect.Descriptor instead.
func (*Integrations_Generation) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Integrations_Generation) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Integrations_Generation) GetCallbackBaseUrl() string {
	if x != nil {
		return x.CallbackBaseUrl
	}
	return ""
}

func (x *Integrations_Generation) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Integrations_Generation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Integrations_Generation) GetPolarstarB2B() *Integrations_PolarStarB2B {
	if x != nil {
		return x.PolarstarB2B
	}
	return nil
}

type Integrations_PolarStarB2B struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 稳定账号身份与供应商签名 body 中的租户身份，不能随凭据轮换改变。
	AccountRef string `protobuf:"bytes,1,opt,name=account_ref,json=accountRef,proto3" json:"account_ref,omitempty"`
	TenantId   string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BaseUrl    string `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// 仅通过环境/Secret 注入；不可复用 local API Key 或 HMAC。
	ApiKey string `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// webhook / lookup_only；后者仅 local 环境且显式禁用回调配置。
	DeliveryMode   string `protobuf:"bytes,5,opt,name=delivery_mode,json=deliveryMode,proto3" json:"delivery_mode,omitempty"`
	CallbackOrigin string `protobuf:"bytes,6,opt,name=callback_origin,json=callbackOrigin,proto3" json:"callback_origin,omitempty"`
	CallbackSecret string `protobuf:"bytes,7,opt,name=callback_secret,json=callbackSecret,proto3" json:"callback_secret,omitempty"`
	// 精确 host 白名单，不支持通配符、端口、URL 或私网地址。
	ResultHostAllowlist   []string             `protobuf:"bytes,8,rep,name=result_host_allowlist,json=resultHostAllowlist,proto3" json:"result_host_allowlist,omitempty"`
	HttpTimeout           *durationpb.Duration `protobuf:"bytes,9,opt,name=http_timeout,json=httpTimeout,proto3" json:"http_timeout,omitempty"`
	ConnectTimeout        *durationpb.Duration `protobuf:"bytes,10,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	ResponseHeaderTimeout *durationpb.Duration `protobuf:"bytes,11,opt,name=response_header_timeout,json=responseHeaderTimeout,proto3" json:"response_header_timeout,omitempty"`
	MaxConnectionsPerHost int32                `protobuf:"varint,12,opt,name=max_connections_per_host,json=maxConnectionsPerHost,proto3" json:"max_connections_per_host,omitempty"`
	MaxResponseBytes      int64                `protobuf:"varint,13,opt,name=max_response_bytes,json=maxResponseBytes,proto3" json:"max_response_bytes,omitempty"`
	MaxResultBytes        int64                `protobuf:"varint,14,opt,name=max_result_bytes,json=maxResultBytes,proto3" json:"max_result_bytes,omitempty"`
	MaxInFlight           int32                `protobuf:"varint,15,opt,name=max_in_flight,json=maxInFlight,proto3" json:"max_in_flight,omitempty"`
	// 轮换重叠期内可接受的上一版本回调密钥；为空表示不启用 previous。
	CallbackPreviousSecret string `protobuf:"bytes,16,opt,name=callback_previous_secret,json=callbackPreviousSecret,proto3" json:"callback_previous_secret,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Integrations_PolarStarB2B) Reset() {
	*x = Integrations_PolarStarB2B{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integrations_PolarStarB2B) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integrations_PolarStarB2B) ProtoMessage() {}

func (x *Integrations_PolarStarB2B) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integrations_PolarStarB2B.ProtoReflect.Descriptor instead.
func (*Integrations_PolarStarB2B) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Integrations_PolarStarB2B) GetAccountRef() string {
	if x != nil {
		return x.AccountRef
	}
	return ""
}

func (x *Integrations_PolarStarB2B) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Integrations_PolarStarB2B) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Integrations_PolarStarB2B) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Integrations_PolarStarB2B) GetDeliveryMode() string {
	if x != nil {
		return x.DeliveryMode
	}
	return ""
}

func (x *Integrations_PolarStarB2B) GetCallbackOrigin() string {
	if x != nil {
		return x.CallbackOrigin
	}
	return ""
}

func (x *Integrations_PolarStarB2B) GetCallbackSecret() string {
	if x != nil {
		return x.CallbackSecret
	}
	return ""
}

func (x *Integrations_PolarStarB2B) GetResultHostAllowlist() []string {
	if x != nil {
		return x.ResultHostAllowlist
	}
	return nil
}

func (x *Integrations_PolarStarB2B) GetHttpTimeout() *durationpb.Duration {
	if x != nil {
		return x.HttpTimeout
	}
	return nil
}

func (x *Integrations_PolarStarB2B) GetConnectTimeout() *durationpb.Duration {
	if x != nil {
		return x.ConnectTimeout
	}
	return nil
}

func (x *Integrations_PolarStarB2B) GetResponseHeaderTimeout() *durationpb.Duration {
	if x != nil {
		return x.ResponseHeaderTimeout
	}
	return nil
}

func (x *Integrations_PolarStarB2B) GetMaxConnectionsPerHost() int32 {
	if x != nil {
		return x.MaxConnectionsPerHost
	}
	return 0
}

func (x *Integrations_PolarStarB2B) GetMaxResponseBytes() int64 {
	if x != nil {
		return x.MaxResponseBytes
	}
	return 0
}

func (x *Integrations_PolarStarB2B) GetMaxResultBytes() int64 {
	if x != nil {
		return x.MaxResultBytes
	}
	return 0
}

func (x *Integrations_PolarStarB2B) GetMaxInFlight() int32 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

func (x *Integrations_PolarStarB2B) GetCallbackPreviousSecret() string {
	if x != nil {
		return x.CallbackPreviousSecret
	}
	return ""
}

type Integrations_Paycores struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// 浏览器支付完成或取消后的本地跳转页，不是支付确认回调地址。
	ReturnUrl     string `protobuf:"bytes,2,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	CancelUrl     string `protobuf:"bytes,3,opt,name=cancel_url,json=cancelUrl,proto3" json:"cancel_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integrations_Paycores) Reset() {
	*x = Integrations_Paycores{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integrations_Paycores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integrations_Paycores) ProtoMessage() {}

func (x *Integrations_Paycores) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integrations_Paycores.ProtoReflect.Descriptor instead.
func (*Integrations_Paycores) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Integrations_Paycores) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Integrations_Paycores) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *Integrations_Paycores) GetCancelUrl() string {
	if x != nil {
		return x.CancelUrl
	}
	return ""
}

type Integrations_AppStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integrations_AppStore) Reset() {
	*x = Integrations_AppStore{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integrations_AppStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integrations_AppStore) ProtoMessage() {}

func (x *Integrations_AppStore) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integrations_AppStore.ProtoReflect.Descriptor instead.
func (*Integrations_AppStore) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 3}
}

func (x *Integrations_AppStore) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

// 审核服务只处理受限用户的提示词，不能接触登录态、余额或生成回调信息。
type Integrations_ContentReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integrations_ContentReview) Reset() {
	*x = Integrations_ContentReview{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integrations_ContentReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integrations_ContentReview) ProtoMessage() {}

func (x *Integrations_ContentReview) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integrations_ContentReview.ProtoReflect.Descriptor instead.
func (*Integrations_ContentReview) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 4}
}

func (x *Integrations_ContentReview) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Integrations_ContentReview) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Integrations_ContentReview) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Integrations_ContentReview) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\x9b\x02\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x120\n" +
	"\bsecurity\x18\x03 \x01(\v2\x14.kratos.api.SecurityR\bsecurity\x12<\n" +
	"\fintegrations\x18\x04 \x01(\v2\x18.kratos.api.IntegrationsR\fintegrations\x12*\n" +
	"\x06worker\x18\x05 \x01(\v2\x12.kratos.api.WorkerR\x06worker\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xf4\x01\n" +
	"\x04Data\x12,\n" +
	"\x05mongo\x18\x01 \x01(\v2\x16.kratos.api.Data.MongoR\x05mongo\x1a\xbd\x01\n" +
	"\x05Mongo\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vreplica_set\x18\x03 \x01(\tR\n" +
	"replicaSet\x123\n" +
	"\x15transactions_required\x18\x04 \x01(\bR\x14transactionsRequired\x120\n" +
	"\x14docker_local_profile\x18\x05 \x01(\bR\x12dockerLocalProfile\"\xa1\x04\n" +
	"\bSecurity\x12.\n" +
	"\x13session_signing_key\x18\x01 \x01(\tR\x11sessionSigningKey\x12=\n" +
	"\x1bgeneration_request_hmac_key\x18\x02 \x01(\tR\x18generationRequestHmacKey\x12?\n" +
	"\x1cgeneration_callback_hmac_key\x18\x03 \x01(\tR\x19generationCallbackHmacKey\x12;\n" +
	"\x1apaycores_callback_hmac_key\x18\t \x01(\tR\x17paycoresCallbackHmacKey\x129\n" +
	"\x19paycores_request_hmac_key\x18\n" +
	" \x01(\tR\x16paycoresRequestHmacKey\x12.\n" +
	"\x13password_memory_kib\x18\x04 \x01(\rR\x11passwordMemoryKib\x12,\n" +
	"\x12password_time_cost\x18\x05 \x01(\rR\x10passwordTimeCost\x121\n" +
	"\x14password_parallelism\x18\x06 \x01(\rR\x13passwordParallelism\x12.\n" +
	"\x13password_salt_bytes\x18\a \x01(\rR\x11passwordSaltBytes\x12,\n" +
	"\x12password_key_bytes\x18\b \x01(\rR\x10passwordKeyBytes\"\x87\f\n" +
	"\fIntegrations\x12C\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2#.kratos.api.Integrations.GenerationR\n" +
	"generation\x12=\n" +
	"\bpaycores\x18\x02 \x01(\v2!.kratos.api.Integrations.PaycoresR\bpaycores\x12>\n" +
	"\tapp_store\x18\x03 \x01(\v2!.kratos.api.Integrations.AppStoreR\bappStore\x12M\n" +
	"\x0econtent_review\x18\x04 \x01(\v2&.kratos.api.Integrations.ContentReviewR\rcontentReview\x1a\xd4\x01\n" +
	"\n" +
	"Generation\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12*\n" +
	"\x11callback_base_url\x18\x02 \x01(\tR\x0fcallbackBaseUrl\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12J\n" +
	"\rpolarstar_b2b\x18\x05 \x01(\v2%.kratos.api.Integrations.PolarStarB2BR\fpolarstarB2b\x1a\xef\x05\n" +
	"\fPolarStarB2B\x12\x1f\n" +
	"\vaccount_ref\x18\x01 \x01(\tR\n" +
	"accountRef\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12#\n" +
	"\rdelivery_mode\x18\x05 \x01(\tR\fdeliveryMode\x12'\n" +
	"\x0fcallback_origin\x18\x06 \x01(\tR\x0ecallbackOrigin\x12'\n" +
	"\x0fcallback_secret\x18\a \x01(\tR\x0ecallbackSecret\x122\n" +
	"\x15result_host_allowlist\x18\b \x03(\tR\x13resultHostAllowlist\x12<\n" +
	"\fhttp_timeout\x18\t \x01(\v2\x19.google.protobuf.DurationR\vhttpTimeout\x12B\n" +
	"\x0fconnect_timeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x0econnectTimeout\x12Q\n" +
	"\x17response_header_timeout\x18\v \x01(\v2\x19.google.protobuf.DurationR\x15responseHeaderTimeout\x127\n" +
	"\x18max_connections_per_host\x18\f \x01(\x05R\x15maxConnectionsPerHost\x12,\n" +
	"\x12max_response_bytes\x18\r \x01(\x03R\x10maxResponseBytes\x12(\n" +
	"\x10max_result_bytes\x18\x0e \x01(\x03R\x0emaxResultBytes\x12\"\n" +
	"\rmax_in_flight\x18\x0f \x01(\x05R\vmaxInFlight\x128\n" +
	"\x18callback_previous_secret\x18\x10 \x01(\tR\x16callbackPreviousSecret\x1ac\n" +
	"\bPaycores\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\x02 \x01(\tR\treturnUrl\x12\x1d\n" +
	"\n" +
	"cancel_url\x18\x03 \x01(\tR\tcancelUrl\x1a%\n" +
	"\bAppStore\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x1a\x8e\x01\n" +
	"\rContentReview\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"g\n" +
	"\x06Worker\x12>\n" +
	"\rpoll_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\fpollInterval\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSizeB(Z&ai-business-service/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),                  // 0: kratos.api.Bootstrap
	(*Server)(nil),                     // 1: kratos.api.Server
	(*Data)(nil),                       // 2: kratos.api.Data
	(*Security)(nil),                   // 3: kratos.api.Security
	(*Integrations)(nil),               // 4: kratos.api.Integrations
	(*Worker)(nil),                     // 5: kratos.api.Worker
	(*Server_HTTP)(nil),                // 6: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),                // 7: kratos.api.Server.GRPC
	(*Data_Mongo)(nil),                 // 8: kratos.api.Data.Mongo
	(*Integrations_Generation)(nil),    // 9: kratos.api.Integrations.Generation
	(*Integrations_PolarStarB2B)(nil),  // 10: kratos.api.Integrations.PolarStarB2B
	(*Integrations_Paycores)(nil),      // 11: kratos.api.Integrations.Paycores
	(*Integrations_AppStore)(nil),      // 12: kratos.api.Integrations.AppStore
	(*Integrations_ContentReview)(nil), // 13: kratos.api.Integrations.ContentReview
	(*durationpb.Duration)(nil),        // 14: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.security:type_name -> kratos.api.Security
	4,  // 3: kratos.api.Bootstrap.integrations:type_name -> kratos.api.Integrations
	5,  // 4: kratos.api.Bootstrap.worker:type_name -> kratos.api.Worker
	6,  // 5: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	7,  // 6: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	8,  // 7: kratos.api.Data.mongo:type_name -> kratos.api.Data.Mongo
	9,  // 8: kratos.api.Integrations.generation:type_name -> kratos.api.Integrations.Generation
	11, // 9: kratos.api.Integrations.paycores:type_name -> kratos.api.Integrations.Paycores
	12, // 10: kratos.api.Integrations.app_store:type_name -> kratos.api.Integrations.AppStore
	13, // 11: kratos.api.Integrations.content_review:type_name -> kratos.api.Integrations.ContentReview
	14, // 12: kratos.api.Worker.poll_interval:type_name -> google.protobuf.Duration
	14, // 13: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	14, // 14: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	10, // 15: kratos.api.Integrations.Generation.polarstar_b2b:type_name -> kratos.api.Integrations.PolarStarB2B
	14, // 16: kratos.api.Integrations.PolarStarB2B.http_timeout:type_name -> google.protobuf.Duration
	14, // 17: kratos.api.Integrations.PolarStarB2B.connect_timeout:type_name -> google.protobuf.Duration
	14, // 18: kratos.api.Integrations.PolarStarB2B.response_header_timeout:type_name -> google.protobuf.Duration
	14, // 19: kratos.api.Integrations.ContentReview.timeout:type_name -> google.protobuf.Duration
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
